import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components'
import { Provider } from "react-redux";
import { Providers } from '@/redux/Providers';
import store from '../redux/store'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Providers>
        <Navbar/>
        {children}
        </Providers>
        </body>
    </html>
  )
}
